-- sdi_tx_sys_tx_sdi_clkout.vhd

-- Generated using ACDS version 22.2 94

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sdi_tx_sys_tx_sdi_clkout is
	port (
		in_clk  : in  std_logic := '0'; --  in_clk.clk
		out_clk : out std_logic         -- out_clk.clk
	);
end entity sdi_tx_sys_tx_sdi_clkout;

architecture rtl of sdi_tx_sys_tx_sdi_clkout is
begin

	out_clk <= in_clk;

end architecture rtl; -- of sdi_tx_sys_tx_sdi_clkout
