// tx_clk_24.v

// Generated using ACDS version 22.2 94

`timescale 1 ps / 1 ps
module tx_clk_24 (
		input  wire  rst,      //   reset.reset
		input  wire  refclk,   //  refclk.clk
		output wire  locked,   //  locked.export
		output wire  outclk_0  // outclk0.clk
	);

	tx_clk_24_altera_iopll_1931_jwjqnjy iopll_0 (
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.locked   (locked),   //  output,  width = 1,  locked.export
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
