-- sdi_tx_sys_tx_core_rst.vhd

-- Generated using ACDS version 22.2 94

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sdi_tx_sys_tx_core_rst is
	port (
		in_reset  : in  std_logic := '0'; --  in_reset.reset
		out_reset : out std_logic         -- out_reset.reset
	);
end entity sdi_tx_sys_tx_core_rst;

architecture rtl of sdi_tx_sys_tx_core_rst is
begin

	out_reset <= in_reset;

end architecture rtl; -- of sdi_tx_sys_tx_core_rst
