-- pll_sys.vhd

-- Generated using ACDS version 22.2 94

library IEEE;
library altera_iopll_1931;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pll_sys is
	port (
		rst      : in  std_logic := '0'; --   reset.reset
		refclk   : in  std_logic := '0'; --  refclk.clk
		locked   : out std_logic;        --  locked.export
		outclk_0 : out std_logic         -- outclk0.clk
	);
end entity pll_sys;

architecture rtl of pll_sys is
	component pll_sys_altera_iopll_1931_xggvo4y_cmp is
		port (
			rst      : in  std_logic := 'X'; -- reset
			refclk   : in  std_logic := 'X'; -- clk
			locked   : out std_logic;        -- export
			outclk_0 : out std_logic         -- clk
		);
	end component pll_sys_altera_iopll_1931_xggvo4y_cmp;

	for iopll_0 : pll_sys_altera_iopll_1931_xggvo4y_cmp
		use entity altera_iopll_1931.pll_sys_altera_iopll_1931_xggvo4y;
begin

	iopll_0 : component pll_sys_altera_iopll_1931_xggvo4y_cmp
		port map (
			rst      => rst,      --   reset.reset
			refclk   => refclk,   --  refclk.clk
			locked   => locked,   --  locked.export
			outclk_0 => outclk_0  -- outclk0.clk
		);

end architecture rtl; -- of pll_sys
