-- tx_clk_148.vhd

-- Generated using ACDS version 22.2 94

library IEEE;
library altera_iopll_1931;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tx_clk_148 is
	port (
		rst      : in  std_logic := '0'; --   reset.reset
		refclk   : in  std_logic := '0'; --  refclk.clk
		locked   : out std_logic;        --  locked.export
		outclk_0 : out std_logic         -- outclk0.clk
	);
end entity tx_clk_148;

architecture rtl of tx_clk_148 is
	component tx_clk_148_altera_iopll_1931_afydldy_cmp is
		port (
			rst      : in  std_logic := 'X'; -- reset
			refclk   : in  std_logic := 'X'; -- clk
			locked   : out std_logic;        -- export
			outclk_0 : out std_logic         -- clk
		);
	end component tx_clk_148_altera_iopll_1931_afydldy_cmp;

	for iopll_0 : tx_clk_148_altera_iopll_1931_afydldy_cmp
		use entity altera_iopll_1931.tx_clk_148_altera_iopll_1931_afydldy;
begin

	iopll_0 : component tx_clk_148_altera_iopll_1931_afydldy_cmp
		port map (
			rst      => rst,      --   reset.reset
			refclk   => refclk,   --  refclk.clk
			locked   => locked,   --  locked.export
			outclk_0 => outclk_0  -- outclk0.clk
		);

end architecture rtl; -- of tx_clk_148
