// fifo_195bit_2048.v

// Generated using ACDS version 22.2 94

`timescale 1 ps / 1 ps
module fifo_195bit_2048 (
		input  wire [194:0] data,    //  fifo_input.datain
		input  wire         wrreq,   //            .wrreq
		input  wire         rdreq,   //            .rdreq
		input  wire         wrclk,   //            .wrclk
		input  wire         rdclk,   //            .rdclk
		input  wire         aclr,    //            .aclr
		output wire [194:0] q,       // fifo_output.dataout
		output wire [10:0]  rdusedw, //            .rdusedw
		output wire [10:0]  wrusedw, //            .wrusedw
		output wire         rdempty, //            .rdempty
		output wire         wrfull   //            .wrfull
	);

	fifo_195bit_2048_fifo_1910_5dgandi fifo_0 (
		.data    (data),    //   input,  width = 195,  fifo_input.datain
		.wrreq   (wrreq),   //   input,    width = 1,            .wrreq
		.rdreq   (rdreq),   //   input,    width = 1,            .rdreq
		.wrclk   (wrclk),   //   input,    width = 1,            .wrclk
		.rdclk   (rdclk),   //   input,    width = 1,            .rdclk
		.aclr    (aclr),    //   input,    width = 1,            .aclr
		.q       (q),       //  output,  width = 195, fifo_output.dataout
		.rdusedw (rdusedw), //  output,   width = 11,            .rdusedw
		.wrusedw (wrusedw), //  output,   width = 11,            .wrusedw
		.rdempty (rdempty), //  output,    width = 1,            .rdempty
		.wrfull  (wrfull)   //  output,    width = 1,            .wrfull
	);

endmodule
